### ISSUE TITLE
Edit checking Lockbox, Receivable Finance became unchecked

### ISSUE THREAD

**Issue by Mberrady** [WorkMAE/CEM-Integration#109]
.  Originally I had only checked ACH and Wires and submitted.  When I edited checking Lockbox, Receivable Finance became uncheck, but the ‘child’ HSBC net and CNX EDI Reports did not.   When Lockbox was unchecked and ACH and Wire remained,the Receivables Finance box became unchecked

**Comment by WorkMAE** [comment]
This should now be fixed, it only unchecks when the parent Receivable finance button is unchecked, not when there are any children unchecked.

**Comment by Mberrady** [comment]
The issue is still pending 
![image](https://user-images.githubusercontent.com/40861938/43611858-8c622372-9678-11e8-9db5-09cd82c23e6d.png)

**Comment by WorkMAE** [comment]
This should now be resolved.  Added an additional check to make sure it unchecks if Receivables Finance is unchecked OR none of the children are checked.

**Comment by Mberrady** [comment]
issue still pending

**Comment by WorkMAE** [comment]
This should be resolved...changed the requirement from checking Receivables Finance service to one of the selected options under Receivables Finance.
