### ISSUE TITLE
Dates showing up as 12/31/1969 if no date is selected on edit

### ISSUE THREAD

**Issue by WorkMAE** [WorkMAE/CEM-Integration#14]
Need to not put in date if no date is present

**Comment by WorkMAE** [comment]
This should be fixed now, failed to check if the date was null or undefined, meaning it defaulted to 12/31/1969 as the default date.

**Comment by jacobdarling** [comment]
In the "critical dates" section, the dates are still showing as 12/31/1969

**Comment by WorkMAE** [comment]
This was already fixed in the Edit view, I went and fixed this in the view View as well.  First pic is Edit view and the second pic is the view View...

In edit mode it will display "format: mm/dd/yyyy" if there is no date and in view mode it will display N/A if there are no dates.

![datespic](https://user-images.githubusercontent.com/31932842/35353978-b732ee10-0140-11e8-91c9-8c0d18346ae2.PNG)
![datepics2](https://user-images.githubusercontent.com/31932842/35354865-5d1d3b9e-0143-11e8-8eeb-4734060192ba.PNG)
