### ISSUE TITLE
Connect Form Button show/hide not working properly

### ISSUE THREAD

**Issue by WorkMAE** [WorkMAE/CEM-Integration#59]
HSBC Connect Form button should only be displayed if the user select any of the following delivery channels. Otherwise, it should be hidden. This is across all request types. 

 
![image](https://user-images.githubusercontent.com/31932842/41390068-19713886-6f62-11e8-95ef-9d52eefb9f11.png)

**Comment by WorkMAE** [comment]
This should now be working as intended

**Comment by CIManager** [comment]
Still not working for receivable. Will test with Payable and Standard Files.

**Comment by CIManager** [comment]
Not working for Standard Files
Only working for Payables.

**Comment by WorkMAE** [comment]
This is now working properly across all channels
